### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sisyphe0713** [sisyphe0713/protospace-30355#1]
# URL
https://protospace-30355.herokuapp.com/

**Comment by erinasan1029** [comment]
宮澤さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀

**Comment by sisyphe0713** [comment]
確認ありがとうございます。

最終課題のご案内もありがとうございます。がんばります💪
